# fly.toml app configuration file generated for jerma-clips on 2023-04-28T17:10:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jerma-clips"
primary_region = "dfw"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
